Добавили 2 функции
htmlacademy-javascript/292701-keksobooking-23 pull request #2
Opened 2021-06-02 17:17 UTC by Georgei-1987

2021-06-04 09:55 UTC, Kirr461 requested changes

2021-06-04 09:55 UTC, Kirr461 commented on js/main.js
> +// https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/random
Советую почитать про JSDoc и сразу стараться хотя бы минимально придерживаться его синтактиса. Можно почитать [тут](https://learn.javascript.ru/comments), ближе к концу есть описание со ссылкой на оригинальный англоязычный русурс.

2021-06-04 09:55 UTC, Kirr461 commented on js/main.js
> +    // console.log('В диапазоне указаны неверные числа.\nВведите пожалуйста правильные числа.');
Лучше выбрасывать ошибку `throw new Error('В диапазоне указаны неверные числа.\nВведите пожалуйста правильные числа.')` или возвращать null. Пустая строка не хорошо потому, что функция начинает возвращать данные разных типов, что может привести к ошибкам при ее вызове.

2021-06-04 09:55 UTC, Kirr461 commented on js/main.js
> +  }
В наших правилах линтера этого нет, но лучше сразу привыкать отступать по фигурных скобок лишнюю строку, так удобнее чатать код (не касается случаев, когда подряд объявляются несколько переменных объектов).

2021-06-04 09:55 UTC, Kirr461 commented on js/main.js
> +  return Math.round((Math.random() * (max - min) + min) * fractionMultiplier) / fractionMultiplier;
Перез `return` тоже лучше оставлять пустую строку.

2021-06-05 09:11 UTC, k-suchkov approved these changes

2021-06-05 09:11 UTC, merged